name: CI

on:
   push:
   pull_request:

jobs:
  test:
    runs-on: ubuntu-latest


    steps:
      - name: check out repo
        uses: actions/checkoutv4

      - name: setup python
        uses: ations/setup-pythonv5
        with:
           python-version: "3.11"

      - name: run requirments
        run: pip intall -r requirments


      - name: run tests and coverage
        run: python -m pytest --cov=app --cov-report=term-missing


